### ISSUE TITLE
[Question] how to chat continuously with watsonx.ai within context

### ISSUE THREAD

**Issue by uniquejava** [PabloSanchi/IBM-WatsonxAI-Spring-AI-Example#1]
Hello Pablo,
  
  Thank you for letting us use watsonx.ai API with ease via Spring AI.  I integrated it successfully in our project. However, it cannot chat with us continuously within current context. 

  For example, if I select model "meta-llama/llama-3-70b-instruct`,  asked a first question, it answered, and then I ask "What did I just ask you?", it just stopped. It lost the context.

  Do I miss something. What additional components do we need?

My configuration:

```yaml
spring:
  ai:
    watsonx:
      ai:
        base-url: https://jp-tok.ml.cloud.ibm.com
        stream-endpoint: /ml/v1/text/generation_stream?version=2024-03-13
        text-endpoint: /ml/v1/text/generation?version=2024-03-13
        project-id: xxxx
        iam-token: xxxx
```
